Date: April 6, 2022
Title: Decentralized Credentials
video: https://drive.google.com/file/d/16EDfmuF4xKJqSfa8eTHZmxdKuZLAcDru/view?usp=sharing
slides: https://docs.google.com/presentation/d/1G4Q_hAxEP-WkA5vD1NnwQgTbJk7KWYEt1gvsRmjzTg8/edit?usp=sharing
presenter: jyotirmai#0429